/*
 * Integrantes:
 * Ileana Pérez Navarro
 * Jacqueline Flores Lares
 */
package ruleta;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ruleta_Loca
 */
public class Ruleta extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    Datos Numero = new Datos();
    Datos Nombre = new Datos();
    String respuesta, uwu, owo;
    
    
    
    /**
     * Creates new form Ruleta
     */
    public String Salida()
    {
        return Numero.SoloSalida();               
    }
    
    
    public Ruleta() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar ventana inicial
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/ruleta.png")).getImage());//agregar un nuevo icono  
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Numero");
        this.Tabla.setModel(modelo);
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        Numero_Lista = new javax.swing.JLabel();
        EntradaNombre = new javax.swing.JTextField();
        EntradaNumero = new javax.swing.JTextField();
        Agregar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Girar = new javax.swing.JToggleButton();
        Ruleta = new javax.swing.JLabel();
        Respuesta = new javax.swing.JTextField();
        Elegir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(60, 81, 52));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(81, 108, 79));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre.setText("Nombre:");

        Numero_Lista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Numero_Lista.setText("Numero de lista:");

        EntradaNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNombreActionPerformed(evt);
            }
        });

        EntradaNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Agregar.setBackground(new java.awt.Color(0, 0, 0));
        Agregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        Girar.setBackground(new java.awt.Color(0, 0, 0));
        Girar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Girar.setForeground(new java.awt.Color(255, 255, 255));
        Girar.setText("¡¡A GIRAR!!");
        Girar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GirarMouseClicked(evt);
            }
        });

        Ruleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Ruleta.gif"))); // NOI18N

        Respuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Elegir.setFont(new java.awt.Font("AR CHRISTY", 0, 24)); // NOI18N
        Elegir.setText("~~EL ELEGIDO ES...~~");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(Elegir)))
                        .addGap(8, 8, 8)
                        .addComponent(Ruleta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addComponent(Numero_Lista))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Agregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(720, 720, 720)
                        .addComponent(Girar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nombre)
                        .addGap(24, 24, 24)
                        .addComponent(Numero_Lista))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EntradaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Agregar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Elegir)
                        .addGap(38, 38, 38)
                        .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ruleta, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Girar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        
        
        if(EntradaNombre.getText().equals("")||EntradaNumero.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Por favor llena correctamente los espacios");
        }
        
        else
        {
            try
            {//capturar un posible error en el bloque 
                Double.parseDouble(EntradaNumero.getText());
            } 
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Una parte necesita numeros explicitamente (El numero de lista) " + e.getMessage());   
            }                        
                    
            modelo.addRow(new Object[]{EntradaNombre.getText(),EntradaNumero.getText()});
            
            
            Numero.inserta(EntradaNumero.getText());              
            Nombre.inserta(EntradaNombre.getText());
            
            EntradaNumero.setText("");
            EntradaNombre.setText("");
        }
        
    }//GEN-LAST:event_AgregarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void EntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNombreActionPerformed

    private void GirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GirarMouseClicked
        
        if(Numero.showOne(0).equals(""))
        {
            JOptionPane.showMessageDialog(null, "No has incluido ninguna persona en la lista");
        }
        else
        {
            Numero.Entrasalida(Numero.showAll(), Nombre.showAll());
            Respuesta.setText(Numero.SoloSalida());   
        }
    }//GEN-LAST:event_GirarMouseClicked

    private void cerrar()
    {
        if(JOptionPane.showConfirmDialog(null,"Realmente deseas cerrar la aplicación","Advertencia",JOptionPane.YES_NO_OPTION)==0)//dentro del dialogo de confirmación viene primero el menmensaje y luego el nombre de la ventana de confirmación, despues otro JoptionPane para que elija un si y un no´para ello esta el if (la respuesta dentro del codigo sera en numeros
        {
            System.exit(0); 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Agregar;
    private javax.swing.JLabel Elegir;
    private javax.swing.JTextField EntradaNombre;
    private javax.swing.JTextField EntradaNumero;
    private javax.swing.JToggleButton Girar;
    private javax.swing.JLabel Numero_Lista;
    private javax.swing.JTextField Respuesta;
    private javax.swing.JLabel Ruleta;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

}
